### PR TITLE
zod-nestjs: Allow using the zodSchema field to construct other types

### PR DESCRIPTION
**Pull request by StevenGBrown**
The static zodSchema field on the DTO classes now maintains the schema
type that is passed in, which allows it to be used to construct other
schemas. Previously this zodSchema field had type "CompatibleZodType"
rather than "T extends CompatibleZodType" which meant that most of the
type information was lost.

Workarounds:
Although not as concise, the schema value can be exported separately or
the zodSchema field can be redefined on each DTO class that needs it.

Breaking change:
The "T" in ZodDtoStatic<T> has changed from the output type to the
schema type. Code that is using the ZodDtoStatic type directly may need
to be updated. No changes are needed if just using the DTOs.

Examples:

```TypeScript
// user.dto.ts

import { createZodDto } from '@anatine/zod-nestjs';
import { z } from 'zod';

const schema = z.object({ name: z.string() });

export class UserDto extends createZodDto(schema) {}

// users-list.dto.ts (has an array of users)

import { createZodDto } from '@anatine/zod-nestjs';
import { z } from 'zod';
import { UserDto } from './user.dto';

// Previously produced a TypeScript error: Property 'array' does not exist on type 'CompatibleZodType'.
const schema = z.object({ items: UserDto.zodSchema.array() });

export class UsersListDto extends createZodDto(schema) {}

// extended-user.dto.ts (a user with an additional field)

import { createZodDto } from '@anatine/zod-nestjs';
import { z } from 'zod';
import { UserDto } from './user.dto';

// Previously produced a TypeScript error: Property 'extend' does not exist on type 'CompatibleZodType'.
const schema = UserDto.zodSchema.extend({ group: z.string() });

export class ExtendedUserDto extends createZodDto(schema) {}
```

### CODE REVIEW

**Review by Brian-McBride — APPROVED** [review]

**Comment by Brian-McBride** [comment]
I'm trying to fix the automated testing, so we can see what actual breaks. 
Although, the Nest plugin could probably use more testing in general. 

When you say breaking change - I see the type changed a bit. Is that resulting in a different schema? If the output remains the same, I'm not sure if it is breaking.

**Comment by StevenGBrown** [comment]
> When you say breaking change - I see the type changed a bit. Is that resulting in a different schema? If the output remains the same, I'm not sure if it is breaking.

ZodDtoStatic is being exported outside of zod-nestjs so if someone is using it directly and specifying the generic type (as something other than any or unknown), that code would need to be updated. Not sure if anyone is doing that though.

Yeah, the type of the DTO classes is unchanged, except that zodSchema is more specific, which should be fine.

**Comment by StevenGBrown** [comment]
@Brian-McBride I've no more changes planned. Would you make a release for me?

zod-nestjs now validates all API requests and responses in the app I'm working on and I've been very happy with it. Love the type safety.

**Comment by Brian-McBride** [comment]
@StevenGBrown It should be in the latest version. 
I did a release a while ago. 

Let me know if that isn't the case

**Comment by StevenGBrown** [comment]
@Brian-McBride the latest version (1.3.0) doesn't have the changes from this PR

**Comment by Brian-McBride** [comment]
This is merged into main. 
I published a 1.3.1 from the main branch again.

**Comment by StevenGBrown** [comment]
That did it, thanks!

**Pull request merged**
